### ISSUE TITLE
Enabling APA citations

### ISSUE THREAD

**Issue by erzk** [UCL/ucl-latex-thesis-templates#11]
First of all, thanks for this template. It's great and saved me a lot of time.
I need to use APA citation style but the [template](https://www.overleaf.com/latex/templates/your-apa6-style-manuscript/kngbbqpypjcq) that I found is using `\documentclass[a4paper,man,natbib]{apa6}` which overwrites the settings from `\documentclass[12pt,phd,draft,a4paper,oneside]{ucl_thesis}`.

What would be a correct way to use APA6 style citation in the ucl_thesis template?

**Comment by ikirker** [comment]
Sorry I missed this when you submitted it: it must have been lost in a bigger pile of notifications.

I'm guessing you might have already found a solution; if so, let me know and I'll just close this with apologies.

From a cursory look, it seems like if you want just the citation style, you probably want to add these lines to `MainPackages.tex` (based on [this TeX Overflow answer](https://tex.stackexchange.com/questions/35809/how-do-i-use-apa-style-citations-with-bibtex)):

```
\usepackage{apacite}
\bibliographystyle{apacite}
```

I haven't tested this yet, though.

**Comment by erzk** [comment]
@ikirker I ended up using the following code in `MainPackages.tex` to get the latest APA-style citation:
```
\usepackage[natbibapa]{apacite}
\usepackage{hyperref}
\makeatletter
\newcommand*{\doi}[1]{\href{https://doi.org/#1}{https://doi.org/#1}}
\renewcommand{\doiprefix}{}
\makeatother
```
Thanks
