### ISSUE TITLE
Use setspace package instead of baselinestretch

### ISSUE THREAD

**Issue by nvesely** [UCL/ucl-latex-thesis-templates#18]
baselinestretch stretch double spaces footnotes and tables, which is not necessary and looks bad. Using the setspace package and setting onehalfspacing only spaces the text body.

**Comment by TomTomRixRix** [comment]
But isn't this already done? In `MainPackages.tex`

```
% The setspace package lets you use 1.5-sized or double line spacing.
\usepackage{setspace}
\setstretch{1.5}

% That just does body text -- if you want to expand *everything*,
%  including footnotes and tables, use this instead:
%\renewcommand{\baselinestretch}{1.5}
```

So you can out comment whatever command you want to choose, either setspace or baselinestretch. 

Perhaps I've understood the issue wrong, then please elaborate a bit more in detail what you would like to be fixed, perhaps with a small example screenshot.

**Comment by nvesely** [comment]
Sorry, should have been more careful in making this PR. I heavily edited the config files and didn’t realize at one point I removed these setspace lines to re-add them months later.
