### ISSUE TITLE
Reset mathcal fonts to default

### ISSUE THREAD

**Issue by psivesely** [UCL/ucl-latex-thesis-templates#19]
`mathptmx` introduces a really terrible font for `mathcal`. Consider adding `\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}` to reset it to the standard alphabet.

**Comment by ikirker** [comment]
(Sorry this took so long to get to, I missed the notifications from this repo. 😓)

I see what you mean. It's a little calligraphically OTT.

With just `mathptmx`:
![Screenshot 2021-05-21 at 15 22 45](https://user-images.githubusercontent.com/479061/119155235-de02be00-ba4a-11eb-9680-b18595206660.png)

With the reset:
![Screenshot 2021-05-21 at 15 22 59](https://user-images.githubusercontent.com/479061/119155280-e8bd5300-ba4a-11eb-9945-eefd420b024b.png)

So, I think the proposed command sets the "alphabet" for `\mathcal` for the OMS encoding block, to the `cmsy` font, `m` series (medium, I think), `n` weight, which is the ordinary default.

Some references for this:

 - <https://www.latex-project.org/help/documentation/encguide.pdf>
 - <https://tex.loria.fr/ctan-doc/macros/latex/doc/html/fntguide/node7.html#SECTION00031000000000000000>
 - <http://web.mit.edu/kolya/.f/root/net.mit.edu/sipb.mit.edu/project/tex-new/doc/latex/base/fntguide/node16.html>

This should be safe to add to the class file, I think.
