### ISSUE TITLE
Share the UCL Thesis template in sharelatex.com

### ISSUE THREAD

**Issue by Botev** [UCL/ucl-latex-thesis-templates#4]
Hi,
First to note I did not found any other means of contacting so my bad for putting this as an issue.

I'm a PhD student at UCL and really appreciate this template. I use a lot sharelatex and wanted to encourage you, or with your consent to share this as an UCL template for thesis there. 

All the best!

**Comment by ikirker** [comment]
This has been done, but ShareLaTeX don't have any sort of process short of mailing their support staff for pulling in updates or improvements, annoyingly. Oh well. :(
