### ISSUE TITLE
"ucl_a4.sty" conflicts with "geometry" package

### ISSUE THREAD

**Issue by jjatria** [UCL/ucl-latex-thesis-templates#6]
Including the `ucl_a4.sty` style makes it impossible to use the `geometry` package: simply loading it (without any options) makes this apparent. Removing `ucl_a4` from the class fixes this with no other noticeable problems.

In fact, I'm not even sure why this style is necessary at all, since all well-behaved packages understand what `a4paper` is.

**Comment by ikirker** [comment]
I think it's probably a legacy thing that should be removed. Will do.

**Comment by ikirker** [comment]
In fact, it looks like I can replace all the size-manipulation shenaniganery in `ucl_thesis.cls` with:

```latex
\RequirePackage[inner=4cm,outer=3cm]{geometry}
```

**Comment by jjatria** [comment]
Isn't it a beauty when legacy code gets so much more simple? :)

Just as an aside, how would that interact with one's own options to geometry?

**Comment by ikirker** [comment]
I'll have to check with some examples, but I think options specified later will just override ones specified earlier. Not sure if there are any non-obvious interactions.

I may also have to tweak chapter headers to be higher up the page to match with the original.

**Comment by ikirker** [comment]
`ucl_a4.sty` appeared to be entirely superfluous anyway. It's been removed as of the current version, and the sizes have been fixed to comply with the regs. I didn't use the geometry package to do it, though (because of the potential for interactions), so I'll need to check the geometry package and the current size settings don't conflict.

**Comment by jjatria** [comment]
Yeah, I noticed that the recent versions did not have `ucl_a4.sty`. Good riddance.

Thanks for looking into this.
