### ISSUE TITLE
MSc option

### ISSUE THREAD

**Issue by victoyip** [UCL/ucl-latex-thesis-templates#8]
How do I add an option for Master of Science (msc) please?

**Comment by messrmo** [comment]
Bit late but I've been writing my masters thesis using a few modifications. You can add it yourself. In the .cls file add these commands at the appropriate locations.

at line 127
`\newcommand \@msc{Master of Science}`

at line 141
`\DeclareOption{msc}{\renewcommand\@degree@string{\@msc}}`

then specify msc in the document class eg.
`\documentclass[12pt,msc,a4paper,oneside]{ucl_thesis}`

**Comment by ikirker** [comment]
Sorry, for some reason I've not been getting notifications from issues in this repo.

I've added a tip/snippet in the Preamble file for overriding the degree title.

**Comment by ikirker** [comment]
In master branch and released to v1.0.4.
